# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CargarCam.ui'
#
# Created: Mon Nov 06 16:34:21 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogCarga(object):
    def setupUi(self, DialogCarga):
        DialogCarga.setObjectName(_fromUtf8("DialogCarga"))
        DialogCarga.setWindowModality(QtCore.Qt.NonModal)
        DialogCarga.setEnabled(True)
        DialogCarga.resize(469, 530)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogCarga.sizePolicy().hasHeightForWidth())
        DialogCarga.setSizePolicy(sizePolicy)
        DialogCarga.setMinimumSize(QtCore.QSize(469, 530))
        DialogCarga.setMaximumSize(QtCore.QSize(469, 530))
        DialogCarga.setAutoFillBackground(False)
        self.layoutWidget = QtGui.QWidget(DialogCarga)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 451, 521))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblTitulo = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Perpetua Titling MT"))
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setObjectName(_fromUtf8("lblTitulo"))
        self.verticalLayout.addWidget(self.lblTitulo)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineTiem = QtGui.QLineEdit(self.layoutWidget)
        self.lineTiem.setFocusPolicy(QtCore.Qt.TabFocus)
        self.lineTiem.setObjectName(_fromUtf8("lineTiem"))
        self.gridLayout.addWidget(self.lineTiem, 8, 2, 1, 1)
        self.lineCiudDest = QtGui.QLineEdit(self.layoutWidget)
        self.lineCiudDest.setFocusPolicy(QtCore.Qt.TabFocus)
        self.lineCiudDest.setObjectName(_fromUtf8("lineCiudDest"))
        self.gridLayout.addWidget(self.lineCiudDest, 4, 2, 1, 1)
        self.lineDist = QtGui.QLineEdit(self.layoutWidget)
        self.lineDist.setFocusPolicy(QtCore.Qt.TabFocus)
        self.lineDist.setObjectName(_fromUtf8("lineDist"))
        self.gridLayout.addWidget(self.lineDist, 6, 2, 1, 1)
        self.lblEmpresa = QtGui.QLabel(self.layoutWidget)
        self.lblEmpresa.setObjectName(_fromUtf8("lblEmpresa"))
        self.gridLayout.addWidget(self.lblEmpresa, 10, 0, 1, 1)
        self.lblID = QtGui.QLabel(self.layoutWidget)
        self.lblID.setObjectName(_fromUtf8("lblID"))
        self.gridLayout.addWidget(self.lblID, 0, 0, 1, 1)
        self.lineCiudOr = QtGui.QLineEdit(self.layoutWidget)
        self.lineCiudOr.setFocusPolicy(QtCore.Qt.TabFocus)
        self.lineCiudOr.setObjectName(_fromUtf8("lineCiudOr"))
        self.gridLayout.addWidget(self.lineCiudOr, 2, 2, 1, 1)
        self.lineID = QtGui.QLineEdit(self.layoutWidget)
        self.lineID.setMouseTracking(True)
        self.lineID.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineID.setObjectName(_fromUtf8("lineID"))
        self.gridLayout.addWidget(self.lineID, 0, 2, 1, 1)
        self.lblCiudOr = QtGui.QLabel(self.layoutWidget)
        self.lblCiudOr.setObjectName(_fromUtf8("lblCiudOr"))
        self.gridLayout.addWidget(self.lblCiudOr, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.lblTiempo = QtGui.QLabel(self.layoutWidget)
        self.lblTiempo.setObjectName(_fromUtf8("lblTiempo"))
        self.gridLayout.addWidget(self.lblTiempo, 8, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.lblDist = QtGui.QLabel(self.layoutWidget)
        self.lblDist.setObjectName(_fromUtf8("lblDist"))
        self.gridLayout.addWidget(self.lblDist, 6, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 7, 0, 1, 1)
        self.lblCiudDest = QtGui.QLabel(self.layoutWidget)
        self.lblCiudDest.setObjectName(_fromUtf8("lblCiudDest"))
        self.gridLayout.addWidget(self.lblCiudDest, 4, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 9, 0, 1, 1)
        self.lineEmp = QtGui.QLineEdit(self.layoutWidget)
        self.lineEmp.setObjectName(_fromUtf8("lineEmp"))
        self.gridLayout.addWidget(self.lineEmp, 10, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 11, 0, 1, 1)
        self.lblHoraS = QtGui.QLabel(self.layoutWidget)
        self.lblHoraS.setObjectName(_fromUtf8("lblHoraS"))
        self.gridLayout.addWidget(self.lblHoraS, 12, 0, 1, 1)
        self.lineHoraS = QtGui.QLineEdit(self.layoutWidget)
        self.lineHoraS.setObjectName(_fromUtf8("lineHoraS"))
        self.gridLayout.addWidget(self.lineHoraS, 12, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 13, 0, 1, 1)
        self.lblImp = QtGui.QLabel(self.layoutWidget)
        self.lblImp.setObjectName(_fromUtf8("lblImp"))
        self.gridLayout.addWidget(self.lblImp, 14, 0, 1, 1)
        self.lineImpor = QtGui.QLineEdit(self.layoutWidget)
        self.lineImpor.setObjectName(_fromUtf8("lineImpor"))
        self.gridLayout.addWidget(self.lineImpor, 14, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.bAgregarAris = QtGui.QPushButton(self.layoutWidget)
        self.bAgregarAris.setObjectName(_fromUtf8("bAgregarAris"))
        self.horizontalLayout.addWidget(self.bAgregarAris)
        self.BCancelar = QtGui.QPushButton(self.layoutWidget)
        self.BCancelar.setObjectName(_fromUtf8("BCancelar"))
        self.horizontalLayout.addWidget(self.BCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblID.setBuddy(self.lineID)
        self.lblCiudOr.setBuddy(self.lineCiudOr)
        self.lblTiempo.setBuddy(self.lineTiem)
        self.lblDist.setBuddy(self.lineDist)
        self.lblCiudDest.setBuddy(self.lineCiudDest)

        self.retranslateUi(DialogCarga)
        QtCore.QMetaObject.connectSlotsByName(DialogCarga)
        DialogCarga.setTabOrder(self.lineID, self.lineCiudOr)
        DialogCarga.setTabOrder(self.lineCiudOr, self.lineCiudDest)
        DialogCarga.setTabOrder(self.lineCiudDest, self.lineDist)
        DialogCarga.setTabOrder(self.lineDist, self.lineTiem)
        DialogCarga.setTabOrder(self.lineTiem, self.lineEmp)
        DialogCarga.setTabOrder(self.lineEmp, self.lineHoraS)
        DialogCarga.setTabOrder(self.lineHoraS, self.lineImpor)
        DialogCarga.setTabOrder(self.lineImpor, self.bAgregarAris)
        DialogCarga.setTabOrder(self.bAgregarAris, self.BCancelar)

    def retranslateUi(self, DialogCarga):
        DialogCarga.setWindowTitle(_translate("DialogCarga", "Cargar Ciudad", None))
        self.lblTitulo.setText(_translate("DialogCarga", "Cargar Camino", None))
        self.lblEmpresa.setText(_translate("DialogCarga", "Empresa:", None))
        self.lblID.setText(_translate("DialogCarga", "&ID Arista: ", None))
        self.lblCiudOr.setText(_translate("DialogCarga", "&Ciudad Origen:", None))
        self.lblTiempo.setText(_translate("DialogCarga", "&Tiempo:", None))
        self.lblDist.setText(_translate("DialogCarga", "D&istancia:", None))
        self.lblCiudDest.setText(_translate("DialogCarga", "Ciudad &Destino:", None))
        self.lblHoraS.setText(_translate("DialogCarga", "Hora Salida:", None))
        self.lblImp.setText(_translate("DialogCarga", "Importe:", None))
        self.bAgregarAris.setText(_translate("DialogCarga", "&Agregar Camino", None))
        self.BCancelar.setText(_translate("DialogCarga", "Ca&ncelar", None))

